import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/lib/auth";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // ✅ fetch session on server
  const session = await getServerSession(authOptions);
  console.log("Session in layout:", session); // debug
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/*  Providers wraps app */}
        <Providers>
          {children}
          {/* Toaster globally here */}
          <Toaster
            position="bottom-left"
            reverseOrder={false}
            toastOptions={{
              duration: 3000, 
              style: {
                borderRadius: "8px",
                color: "#fff",
              },
            }}
          />
        </Providers>
      </body>
    </html>
  );
}
